# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Filippo Tosetto
tagline:          'iOS Developer'
description:      'Things about me'
url:              http://filippotosetto.github.io
baseurl:          /

author:
  name:              Filippo Tosetto
  url:               https://twitter.com/filippotosetto
  email:             filippo.tosetto@gmail.com

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde

# Custom collection
collections:
  project:
    output: true

gems: [jekyll-paginate]
